# Generated by Django 3.1.2 on 2020-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
